### ISSUE TITLE
Feature: Mark Atlas-Unknown Maps

### ISSUE THREAD

**Issue by IeUDE** [zaafar/poehud_mapsexchange#1]
Hello,

would it be possible to add such a feature (enable/disable)?

Highlight (small star/dot/etc) maps in inventory/stash that are still unknown in the atlas?

ty!

**Comment by zaafar** [comment]
that would be nice plugin, however would require lot of work as currently this isn't possible in poehud.

**Comment by zaafar** [comment]
no need to do that as it's a built in feature of map stash tab.
