### ISSUE TITLE
Map stash tab count

### ISSUE THREAD

**Issue by github23leech** [zaafar/poehud_mapsexchange#3]
Somehow it's not counting the maps inside the map stash tab, otherwise it's working fine.

**Comment by zaafar** [comment]
what do you mean not counting maps inside the map stash tab???
Please show using print screen, thx.

**Comment by github23leech** [comment]
![mapstash](https://user-images.githubusercontent.com/22951362/41825058-bef76828-781a-11e8-8655-00240a83b08d.jpeg)


So it only shows the open tab, not all maps within the map stash tab.

**Comment by zaafar** [comment]
oh that...yeah it is not updated to handle "non-opened" map tab in map-stash-tab....
it was developed before poe had map stash tab.

**Comment by zaafar** [comment]
done.
